inventory_app/urls.py
from django.contrib import admin
from django.urls import path, include
from productapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('product/',include('productapp.urls', namespace="Product"))
]

productapp/urls.py
from django.urls import path, re_path
from django.views.generic import UpdateView

from productapp import views
from productapp.forms import ProductForm
from productapp.models import Product

app_name="Product"
urlpatterns=[
    path('showproducts', views.get_product.as_view(),name='product_list'),
    #path('<int:pk>',views.product_detail.as_view()),
    #re_path(r'^(?P<pk>[0-9]+)$',views.product_detail.as_view(),name='product_detail'),
    re_path(r'^(?P<product_id>[0-9]+)$',views.product_detail,name='product_detail'),
    #path('new',views.ProductCreate.as_view()),
    path('new', views.product_new),
    #path("<int:product_id>/update",views.product_update)
    path('<int:pk>/update',UpdateView.as_view(model=Product,template_name='productapp/product_update.html',form_class=ProductForm))
]

productapp/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=30)
    price=models.FloatField()
    description=models.CharField(max_length=50)
    quantity=models.IntegerField()

    def get_absolute_url(self):
        return reverse('Product:product_list')

productapp/forms.py
from django import forms
from productapp.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields='__all__'
        #exclude=(id)

productapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView
from productapp.forms import ProductForm
from productapp.models import Product

def home(request):
    return render(request,'home.html')

#def get_product(request):
#    prods=Product.objects.all()
#    return render(request,'productapp/product.html',{'Products':prods})

def product_detail(request,product_id):
     #prod=Product.objects.filter(id=product_id)
     prod=get_object_or_404(Product,id=product_id)
     return render(request,'productapp/product_detail.html',{'object':prod})


class get_product(ListView):
     model = Product
     template_name = 'productapp/product.html'

#class product_detail(DetailView):
#     template_name = 'productapp/product_detail.html'
#     model = Product

class ProductCreate(CreateView):
     model = Product
     form_class = ProductForm
     template_name = 'productapp/product_new.html'
     success_url = reverse_lazy('Product:product_list')

def product_new(request):
     if request.method=='GET':
          return render(request, 'productapp/product_new.html', {'form': ProductForm})
     else:
          form=ProductForm(request.POST)
          if form.is_valid():
                form.save(commit=True)
                return HttpResponseRedirect(reverse('Product:product_list'))
          else:
               return render(request, 'productapp/product_new.html', {'form': ProductForm})

def product_update(request,product_id):
     prod=get_object_or_404(Product,id=product_id)
     form=ProductForm(request.POST or None,instance=prod)
     if request.method=='POST':
          if form.is_valid():
               form.save()
               return HttpResponseRedirect(reverse('Product:product_list'))
     else:
         return render(request,'productapp/product_update.html',{'form':form})

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Welcome to the inventory website</h1>
</body>
</html>

templates/productapp/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for p in object_list %}
Name: <a href="{% url 'Product:product_detail' p.id %}">{{p.name}}</a><br>
Price: {{p.price}}<br>
Description: {{p.description}}<br>
Quantity: {{p.quantity}}<br><br>
{% endfor %}
</body>
</html>

templates/productapp/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{object.name}}<br>
{{object.price}}<br>
{{object.description}}<br>
{{object.quantity}}<br>
</body>
</html>

templates/productapp/product_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="save">Save</button>
</form>
</body>
</html>

templates/productapp/product_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="save">Save</button>
</form>
</body>
</html>